"""
Pydantic data models for the fraud detection dataset generator.
"""

from typing import List, Dict, Any, Optional
from datetime import datetime
from pydantic import BaseModel, Field, validator


class TranscriptLine(BaseModel):
    """A single line of conversation transcript."""
    speaker: str = Field(..., description="Either 'Agent' or 'Customer'")
    text: str = Field(..., description="The spoken text")
    timestamp_end: float = Field(..., ge=0, description="Cumulative seconds from call start")
    
    @validator('speaker')
    def validate_speaker(cls, v):
        if v not in ['Agent', 'Customer']:
            raise ValueError('Speaker must be either "Agent" or "Customer"')
        return v


class MultimodalAnalysis(BaseModel):
    """Audio analysis data for the conversation."""
    dominant_emotion: str = Field(..., description="Primary emotional tone")
    secondary_emotion: str = Field(..., description="Secondary emotional undertone")
    pace: str = Field(..., description="Conversation speed")
    confidence_score: float = Field(..., ge=0.0, le=1.0, description="Analysis confidence")


class KeyEntities(BaseModel):
    """Structured entity extraction for NER training."""
    organization: List[str] = Field(default_factory=list, description="Banks, companies, organizations mentioned")
    product: List[str] = Field(default_factory=list, description="Banking products/services mentioned")
    pii_requested: List[str] = Field(default_factory=list, description="Personal information requested by agent")


class ChunkLevelAnalysis(BaseModel):
    """Progressive fraud detection analysis at a specific timestamp."""
    timestamp: float = Field(..., ge=0, description="Timestamp in seconds")
    verdict_at_chunk: str = Field(..., description="YES or NO verdict at this timestamp")
    rationale_at_chunk: str = Field(..., description="Explanation of verdict at this timestamp")
    
    @validator('verdict_at_chunk')
    def validate_verdict(cls, v):
        if v not in ['YES', 'NO']:
            raise ValueError('Verdict at chunk must be either "YES" or "NO"')
        return v


class GenerationMetadata(BaseModel):
    """Metadata about the generation process."""
    target_duration: float = Field(..., description="Target conversation duration in seconds")
    actual_duration: float = Field(..., description="Actual conversation duration in seconds")
    multiplier_round: int = Field(default=1, description="Which variation round this is")
    combination_key: str = Field(..., description="Unique combination identifier")
    generated_at: str = Field(..., description="ISO timestamp of generation")


class ScenarioInfo(BaseModel):
    """Information about a fraud detection scenario."""
    scenario_id: int = Field(..., description="Unique scenario identifier")
    description: str = Field(..., description="Scenario description")
    case_type: str = Field(..., description="Type of case (fraud, normal, etc.)")
    policy: str = Field(..., description="Relevant policy rules")


class PersonaCombination(BaseModel):
    """A combination of agent and customer personas with scenario."""
    session_id: int = Field(..., description="Unique session identifier")
    agent_persona: str = Field(..., description="Agent personality description")
    customer_persona: str = Field(..., description="Customer personality description")
    scenario: ScenarioInfo = Field(..., description="Scenario information")
    multiplier_round: int = Field(default=1, description="Which variation round this is")
    combination_key: str = Field(..., description="Unique combination identifier")


class SourceConversation(BaseModel):
    """Complete source conversation generated by the LLM with enhanced schema."""
    # Core conversation data
    transcript: List[TranscriptLine] = Field(..., description="Conversation transcript")
    multimodal_analysis: MultimodalAnalysis = Field(..., description="Audio analysis")
    
    # Enhanced fields for better training
    key_entities: KeyEntities = Field(..., description="Structured entity extraction")
    chunk_level_analysis: List[ChunkLevelAnalysis] = Field(..., description="Progressive fraud detection analysis")
    
    # Final analysis
    final_slow_thinking_rationale: str = Field(..., description="Detailed reasoning")
    final_verdict: str = Field(..., description="YES for fraud, NO for legitimate")
    violated_policies: List[str] = Field(default_factory=list, description="List of violated policy rules")
    scam_outcome: str = Field(..., description="Successful/Failed/Interrupted/N/A")
    
    # Top-level metadata for easy access
    session_id: int = Field(..., description="Unique session identifier")
    agent_persona: str = Field(..., description="Agent personality used")
    customer_persona: str = Field(..., description="Customer personality used")
    scenario: ScenarioInfo = Field(..., description="Scenario used")
    
    # Generation metadata
    generation_metadata: GenerationMetadata = Field(..., description="Generation process metadata")
    
    @validator('final_verdict')
    def validate_verdict(cls, v):
        if v not in ['YES', 'NO']:
            raise ValueError('Final verdict must be either "YES" or "NO"')
        return v
    
    @validator('scam_outcome')
    def validate_scam_outcome(cls, v):
        valid_outcomes = ['Successful', 'Failed', 'Interrupted', 'N/A']
        if v not in valid_outcomes:
            raise ValueError(f'Scam outcome must be one of {valid_outcomes}')
        return v
    
    @validator('transcript')
    def validate_transcript_order(cls, v):
        """Ensure timestamps are in ascending order."""
        for i in range(1, len(v)):
            if v[i].timestamp_end <= v[i-1].timestamp_end:
                raise ValueError('Transcript timestamps must be in ascending order')
        return v
    
    @validator('chunk_level_analysis')
    def validate_chunk_analysis_order(cls, v):
        """Ensure chunk analysis timestamps are in ascending order."""
        for i in range(1, len(v)):
            if v[i].timestamp <= v[i-1].timestamp:
                raise ValueError('Chunk analysis timestamps must be in ascending order')
        return v


class TrainingChunk(BaseModel):
    """A training data chunk representing a cumulative conversation state."""
    session_id: int = Field(..., description="Source session identifier")
    chunk_timestamp: float = Field(..., description="Timestamp for this chunk")
    cumulative_transcript: List[TranscriptLine] = Field(..., description="Transcript up to this point")
    cumulative_audio_analysis: MultimodalAnalysis = Field(..., description="Audio analysis for this chunk")
    slow_thinking_rationale: str = Field(..., description="Reasoning for this timestamp")
    final_verdict: str = Field(..., description="Verdict at this timestamp")
    
    # Metadata
    scenario_info: Dict[str, Any] = Field(..., description="Scenario information")
    combination_key: str = Field(..., description="Source combination identifier")
    multiplier_round: int = Field(default=1, description="Variation round")
    generated_at: datetime = Field(default_factory=datetime.now, description="Generation timestamp")
    
    @validator('final_verdict')
    def validate_verdict(cls, v):
        if v not in ['YES', 'NO']:
            raise ValueError('Final verdict must be either "YES" or "NO"')
        return v


class GenerationStats(BaseModel):
    """Statistics for the generation process."""
    total_combinations: int = Field(..., description="Total number of combinations")
    completed_conversations: int = Field(default=0, description="Completed source conversations")
    total_training_chunks: int = Field(default=0, description="Total training chunks generated")
    failed_generations: int = Field(default=0, description="Number of failed generations")
    start_time: datetime = Field(default_factory=datetime.now, description="Generation start time")
    end_time: Optional[datetime] = Field(None, description="Generation end time")
    
    @property
    def success_rate(self) -> float:
        """Calculate the success rate of generation."""
        if self.total_combinations == 0:
            return 0.0
        return (self.completed_conversations / self.total_combinations) * 100
    
    @property
    def duration_minutes(self) -> float:
        """Calculate generation duration in minutes."""
        if self.end_time is None:
            end_time = datetime.now()
        else:
            end_time = self.end_time
        return (end_time - self.start_time).total_seconds() / 60
